In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {"Name":["Mia","Alice","JK"],
        "Age":[22,25,20],
        "City":["LA","UK","Norway"]}

df = pd.DataFrame(data)
print(df)

    Name  Age    City
0    Mia   22      LA
1  Alice   25      UK
2     JK   20  Norway

In [3]:
employee_data = {"EmployeeID":[101,102,103],
                  "Name":["Mia","Joe","JC"],
                 "Salary":[5000,5500,4500],
                 "Full Time":[True,True,False]}
df = pd.DataFrame(employee_data)
print(df)

   EmployeeID Name  Salary  Full Time
0         101  Mia    5000       True
1         102  Joe    5500       True
2         103   JC    4500      False

In [6]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], columns = ["A","B","C"])
print(df)

    A   B   C
0   1   2   3
1   4   5   6
2   7   8   9
3  11  12  13

In [8]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[11,12,13]], columns = ["A","B","C"], index = ["W","X","Y","Z"])
print(df)

    A   B   C
W   1   2   3
X   4   5   6
Y   7   8   9
Z  11  12  13

In [12]:
df.index
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, W to Z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes

In [13]:
df.describe()

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.750000   6.750000   7.750000
std     4.272002   4.272002   4.272002
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     8.000000   9.000000  10.000000
max    11.000000  12.000000  13.000000

In [15]:
df["A"].unique()
df["B"].unique()

array([ 2,  5,  8, 12])

In [19]:
df.nunique()
#df.shape

A    4
B    4
C    4
dtype: int64

In [21]:
df.size

12

In [22]:
df.head(2)

   A  B  C
W  1  2  3
X  4  5  6

In [23]:
df.tail(2)

    A   B   C
Y   7   8   9
Z  11  12  13

# **Accessing data in pd.DataFrame**

In [29]:
data = {"Name":["Mia","JC","CK"],
        "Age":[25,19,45],
        "Salary":[4500,3000,5000]}


df = pd.DataFrame(data)
print(df)

df["Age"]
df[["Name","Salary"]]

  Name  Age  Salary
0  Mia   25    4500
1   JC   19    3000
2   CK   45    5000

  Name
0  Mia
1   JC
2   CK

In [30]:
df.loc[:,["Name"]]

  Name
0  Mia
1   JC
2   CK

In [31]:
df.iloc[:,[0,2]]

  Name  Salary
0  Mia    4500
1   JC    3000
2   CK    5000

In [32]:
df["Country"]="Myanmar"
print(df)

  Name  Age  Salary  Country
0  Mia   25    4500  Myanmar
1   JC   19    3000  Myanmar
2   CK   45    5000  Myanmar

In [34]:
df["Age Group"] =["Adult","Young","Adult"]
print(df)

  Name  Age  Salary  Country Age Group
0  Mia   25    4500  Myanmar     Adult
1   JC   19    3000  Myanmar     Young
2   CK   45    5000  Myanmar     Adult

In [55]:
df["Tax"] = df["Salary"]*0.05
print(df)

  Name  Age  Salary  Country Age Group    Tax
0  Mia   25    4500  Myanmar     Adult  225.0
1   JC   19    3000  Myanmar     Young  150.0
2   CK   45    5000  Myanmar     Adult  250.0

# Deleting the current data

In [56]:
df = df.drop(columns = ["Tax"])
print(df)

  Name  Age  Salary  Country Age Group
0  Mia   25    4500  Myanmar     Adult
1   JC   19    3000  Myanmar     Young
2   CK   45    5000  Myanmar     Adult

# Delete using -del- method

In [59]:
del df["Age Group"]
print(df)

  Name  Age  Salary
0  Mia   25    4500
1   JC   19    3000
2   CK   45    5000

# Filtering

In [60]:
data = {"Name":["Mia","JC","CK","IC"],
        "Age":[25,19,45,30],
        "Salary":[4500,3000,5000,4700]}
df = pd.DataFrame(data)
print(df)

  Name  Age  Salary
0  Mia   25    4500
1   JC   19    3000
2   CK   45    5000
3   IC   30    4700

In [61]:
df[ df["Age"] > 27]

  Name  Age  Salary
2   CK   45    5000
3   IC   30    4700

In [63]:
df[(df["Age"] >= 25) & (df["Age"] <= 30) ]
df[df["Salary"] != 3000 ]

  Name  Age  Salary
0  Mia   25    4500
2   CK   45    5000
3   IC   30    4700

#Sorting using .sort_values()

In [64]:
df.sort_values("Age")

  Name  Age  Salary
1   JC   19    3000
0  Mia   25    4500
3   IC   30    4700
2   CK   45    5000

In [67]:
df.sort_values("Salary", ascending= False)

  Name  Age  Salary
2   CK   45    5000
3   IC   30    4700
0  Mia   25    4500
1   JC   19    3000

In [68]:
df.sort_values("Salary", ascending= True)

  Name  Age  Salary
1   JC   19    3000
0  Mia   25    4500
3   IC   30    4700
2   CK   45    5000

In [69]:
df.sort_values(["Age","Salary"], ascending = [True,False])

  Name  Age  Salary
1   JC   19    3000
0  Mia   25    4500
3   IC   30    4700
2   CK   45    5000

# Grouping using .groupby()

In [71]:
data = {"Name":["Mia","JC","CK","IC","Evonne","Caster","Tresure","Joko","Moko"],
        "City":["RGN","MDY","TGI","TGI","RGN","RGN","MDY","MON","DWE"],
        "Age":[25,19,45,29,30,18,23,34,27],
        "Salary":[4500,3000,5000,4700,5000,2300,3200,5300,4000]}
df = pd.DataFrame(data)
print(df)

      Name City  Age  Salary
0      Mia  RGN   25    4500
1       JC  MDY   19    3000
2       CK  TGI   45    5000
3       IC  TGI   29    4700
4   Evonne  RGN   30    5000
5   Caster  RGN   18    2300
6  Tresure  MDY   23    3200
7     Joko  MON   34    5300
8     Moko  DWE   27    4000

In [72]:
df.groupby("City")["Salary"].mean()

City
DWE    4000.000000
MDY    3100.000000
MON    5300.000000
RGN    3933.333333
TGI    4850.000000
Name: Salary, dtype: float64

In [73]:
df.groupby("City")["Name"].count()

City
DWE    1
MDY    2
MON    1
RGN    3
TGI    2
Name: Name, dtype: int64

In [74]:
df.groupby("City")["Age"].max()

City
DWE    27
MDY    23
MON    34
RGN    30
TGI    45
Name: Age, dtype: int64

In [75]:
df.groupby("City")["Age"].min()

City
DWE    27
MDY    19
MON    34
RGN    18
TGI    29
Name: Age, dtype: int64

# Descriptive Statistic

```
#.decribe() method can only applied to numeric value column. not to string
```

In [76]:
df.describe()

             Age       Salary
count   9.000000     9.000000
mean   27.777778  4111.111111
std     8.257993  1051.718171
min    18.000000  2300.000000
25%    23.000000  3200.000000
50%    27.000000  4500.000000
75%    30.000000  5000.000000
max    45.000000  5300.000000

In [77]:
#.decribe() method can only applied to numeric value column. not to string
df["Salary"].describe()

count       9.000000
mean     4111.111111
std      1051.718171
min      2300.000000
25%      3200.000000
50%      4500.000000
75%      5000.000000
max      5300.000000
Name: Salary, dtype: float64

In [78]:
df["Age"].mean()

np.float64(27.77777777777778)

In [79]:
df["Salary"].min(), df["Salary"].max()

(2300, 5300)

# Handle missing values

```
using .fillna() or .dropna()
```

In [80]:
data = {"Name":["Aung","Chaw","Su","Hla","Moe"],
        "Age":[25,np.nan,28,np.nan,35],
        "Salary":[3000,4500,np.nan,5000,np.nan],
        "City": ["RGN","DWE",None,"MDY","RGN"]}

df = pd.DataFrame(data)
print(df)

   Name   Age  Salary  City
0  Aung  25.0  3000.0   RGN
1  Chaw   NaN  4500.0   DWE
2    Su  28.0     NaN  None
3   Hla   NaN  5000.0   MDY
4   Moe  35.0     NaN   RGN

In [86]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    25.0
3    25.0
Name: Age, dtype: float64

In [87]:
df.dropna(subset=["Salary"], inplace = True)
print(df)

   Name   Age  Salary City
0  Aung  25.0  3000.0  RGN
1  Chaw   NaN  4500.0  DWE
3   Hla   NaN  5000.0  MDY